### ISSUE TITLE
Upgrade python-docx to 0.8.2. breaks script

### ISSUE THREAD

**Issue by tooh** [fokoenecke/html_docx#3]
Upgrading to python-docx 0.8.2  caused this error

```
File "/Scripts/html/tag_dispatchers/__init__.py", line 5, in <module>
    from docx.text import Paragraph
ImportError: cannot import name Paragraph
```

**Comment by tooh** [comment]
changed in all relevant files in tag_dispatchers

```
from docx.text import Paragraph
```

to

```
from docx.text.paragraph import Paragraph
```

**Comment by tooh** [comment]
@fokoenecke Can you help me on this.

Above change was not the solution. When I run my script with real data I now get :

```
Traceback (most recent call last):
  File "create_releasenotes.py", line 686, in <module>
    main()
  File "create_releasenotes.py", line 197, in main
    read_stories(url,file_name,template)
  File "create_releasenotes.py", line 523, in read_stories
    add_html(paragraph_detail, html)
  File "/Users/peter/iApp/ScrumDoPy/Scripts/html/__init__.py", line 14, in add_html
    builder.from_html_tree(root=root)
  File "/Users/peter/iApp/ScrumDoPy/Scripts/html/converter.py", line 23, in from_html_tree
    self._append_docx_elements(root, self._root_container)
  File "/Users/peter/iApp/ScrumDoPy/Scripts/html/converter.py", line 35, in _append_docx_elements
    new_container = dispatcher.append_head(html_element, container)
  File "/Users/peter/iApp/ScrumDoPy/Scripts/html/tag_dispatchers/paragraph.py", line 15, in append_head
    paragraph = cls.get_new_paragraph(container)
  File "/Users/peter/iApp/ScrumDoPy/Scripts/html/tag_dispatchers/__init__.py", line 45, in get_new_paragraph
    if isinstance(container, Document):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

I do not master python enough to figure this out.

**Comment by fokoenecke** [comment]
I didn't have the time to check the changes made in recent python-docx updates. It seems the structure changed in some places, so my imports are broken now. The Document class is now located in docx.document, not in docx.api. You should be able to solve the problem by changing the Document import to:

``` python
from docx.document import Document
```

I am pretty sure that there will be more errors like this on the road :(
edit: although describing it right, i wrote the wrong code.

**Comment by tooh** [comment]
@fokoenecke Thanks for looking into this. You were right I encounter more errors on the road.

I will follow your advice and contact @scanny. 
I'm sure there must be a strong business case for some extension to python_docx to handle markdown.

**Comment by scanny** [comment]
I think you want the import:

``` python
from docx.document import Document
```

The docx.api.Document object is a (factory) function that creates a docx.document.Document object.

**Comment by fokoenecke** [comment]
@tooh I think there are ways to include the code in a way that will throw an exception, if the specific function is called, but the package is not innstalled. That would not interfere with the rest of python-docx.

I changed my code to match the changes in python-docx.
Let me know, if this helps you, too.
My main problem was, that there is a new style handling. I assinged them more in a trial and error way before. This does not work anymore. So there could be problems if your styles are not named in a default way.

**Comment by scanny** [comment]
As it happens I was working on a RestructuredText to docx translator last week, supporting just enough syntax to get the job done for my common projects. The same challenge arises there, having to assume which styles to use for paragraphs, list items, strong, emphasis, etc.

The way I solved it was by having a dictionary of default style name mappings that could be overridden in the "translate" call to change the mappings to custom styles as necessary.

For whatever it's worth :)

As discussed on other related issue threads, it's unlikely that any particular simplified markup translator will be built into python-docx, primarily because there are so many of them. What _is_ likely is that eventually we'll have an HTML translator built in, which most simplified markup languages can be translated into. Since `lxml` is already a dependency, we'll probably use that package's HTML parsing capability to do the needful parsing-wise.

**Comment by scanny** [comment]
Here's the translator code in a Gist in case anyone wants to take a look:
https://gist.github.com/scanny/4476085aa5f57b8b4fc0
